const assert=require('node:assert/strict');
const test=require('node:test');
const GameRules=require('../game-rules.js');
const run=(state,frame={})=>GameRules.step(state,{dt:frame.dt??16,input:frame.input||{},random:frame.random||(()=>.5)});

test('moves within the lower sixty percent and supports diagonal input',()=>{let s=GameRules.create({player:{x:210,y:630}});s=run(s,{dt:100,input:{left:true,up:true}}).state;assert.deepEqual([s.player.x,s.player.y],[178,598]);s=run(GameRules.create({player:{x:0,y:288}}),{dt:1000,input:{left:true,up:true}}).state;assert.deepEqual([s.player.x,s.player.y],[0,288]);});
test('fires from the moved player position and double spread produces three shots',()=>{let s=GameRules.create({player:{x:210,y:630},fireClock:90,doubleMs:8000,spreadMs:8000});s=run(s,{dt:0,input:{up:true}}).state;assert.equal(s.bullets.length,3);assert.equal(s.bullets[0].y,621);});
test('consumes an enemy bullet once on collision',()=>{let s=GameRules.create({player:{x:210,y:630,lives:3},enemyBullets:[{x:235,y:650,w:8,h:14,vx:0,vy:0}]});s=run(s).state;assert.equal(s.player.lives,2);assert.equal(s.enemyBullets.length,0);});
test('spawns all three enemy kinds from deterministic rolls',()=>{for(const [roll,kind]of [[.2,'normal'],[.6,'fast'],[.9,'elite']]){let s=GameRules.create({score:500,spawnClock:700});s=run(s,{dt:0,random:()=>roll}).state;assert.equal(s.enemies[0].kind,kind)}});
test('uses the documented four powerup drop ranges',()=>{for(const [roll,kind]of [[.024,'shield'],[.025,'spread'],[.055,'double'],[.09,'heal']]){let s=GameRules.create({bullets:[{x:200,y:190,w:8,h:17,vx:0,vy:0}],enemies:[{kind:'normal',x:190,y:180,w:38,h:38,hp:1,score:100,speed:0}]});s=run(s,{dt:0,random:()=>roll}).state;assert.equal(s.powerups[0].kind,kind)}let s=GameRules.create({bullets:[{x:200,y:190,w:8,h:17,vx:0,vy:0}],enemies:[{kind:'normal',x:190,y:180,w:38,h:38,hp:1,score:100,speed:0}]});s=run(s,{dt:0,random:()=>.1}).state;assert.equal(s.powerups.length,0)});
test('healing restores one life, consumes at full life, and expires its effect',()=>{let s=GameRules.create({player:{x:210,y:630,lives:2},powerups:[{kind:'heal',x:220,y:635,w:28,h:28,vy:100}]});let r=run(s,{dt:0});assert.equal(r.state.player.lives,3);assert.equal(r.state.powerups.length,0);assert.equal(r.state.healFlashMs,700);assert.ok(r.events.some(e=>e.type==='life-restored'));r=run(r.state,{dt:700});assert.equal(r.state.healFlashMs,0);s=GameRules.create({player:{x:210,y:630,lives:3},powerups:[{kind:'heal',x:220,y:635,w:28,h:28,vy:100}]});r=run(s,{dt:0});assert.equal(r.state.player.lives,3);assert.equal(r.state.powerups.length,0);assert.equal(r.state.healFlashMs,0);assert.ok(!r.events.some(e=>e.type==='life-restored'))});
test('triggers Boss 1 once, awards two thousand, and grants ranking eligibility',()=>{let s=GameRules.create({score:10000});let r=run(s,{dt:0});assert.equal(r.state.boss.stage,1);assert.ok(r.events.some(e=>e.type==='boss-started'));s=GameRules.create({score:10000,boss:{stage:1,trigger:10000,x:160,y:70,w:160,h:120,hp:1,maxHp:1,attackClock:0,pattern:0,phase:0},bullets:[{x:200,y:100,w:8,h:17,vx:0,vy:0}]});r=run(s,{dt:0});assert.equal(r.state.score,12000);assert.equal(r.state.rankEligible,true);assert.ok(r.events.some(e=>e.type==='boss-defeated'));assert.ok(r.events.some(e=>e.type==='ranking-unlocked'));});
test('emits a run-ended event for death and final victory while paused time does not advance',()=>{let s=GameRules.create({elapsedMs:1000,status:'paused'});assert.equal(run(s,{dt:2000}).state.elapsedMs,1000);s=GameRules.create({player:{x:210,y:630,lives:1},enemyBullets:[{x:235,y:650,w:8,h:14,vx:0,vy:0}]});let r=run(s);assert.equal(r.state.status,'over');assert.ok(r.events.some(e=>e.type==='run-ended'&&e.reason==='death'));s=GameRules.create({score:100000,boss:{stage:4,trigger:100000,x:160,y:70,w:160,h:120,hp:1,maxHp:1,attackClock:0,pattern:0,phase:0},bullets:[{x:200,y:100,w:8,h:17,vx:0,vy:0}]});r=run(s,{dt:0});assert.equal(r.state.status,'success');assert.ok(r.events.some(e=>e.type==='run-ended'&&e.reason==='victory'));});
