import { AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame } from 'remotion';

export const NEON_SHOTS = {open:{from:0,duration:65},battlefield:{from:65,duration:70},fighters:{from:135,duration:51},outro:{from:186,duration:54}} as const;
export const NEON_TOTAL = 240;
// Compatibility export for unused Ink Press scene files retained with the template.
export const AIFL_SHOTS = {morning:NEON_SHOTS.open,outro:NEON_SHOTS.outro} as const;
const brand={ink:'#05061a',cyan:'#58e7ff',pink:'#ff71b5',gold:'#ffc75a',text:'#eef0ff'};
const ease=(frame:number,from:number,duration:number)=>spring({frame:Math.max(0,frame-from),fps:30,config:{damping:200,stiffness:120}});

const Wordmark:React.FC<{small?:boolean}>=({small=false})=>{const frame=useCurrentFrame(),progress=ease(frame,6,26);return <div style={{display:'flex',alignItems:'center',gap:small?18:26,opacity:interpolate(progress,[0,1],[0,1]),transform:`translateY(${interpolate(progress,[0,1],[18,0])}px)`}}><div style={{width:small?26:42,height:small?26:42,border:`2px solid ${brand.cyan}`,transform:'rotate(45deg)',boxShadow:`0 0 25px ${brand.cyan}`,display:'grid',placeItems:'center'}}><div style={{width:small?9:15,height:small?9:15,background:brand.pink,boxShadow:`0 0 18px ${brand.pink}`}}/></div><div><div style={{fontSize:small?18:27,letterSpacing:small?5:9,color:'#aeb9ff',fontWeight:800}}>NEON FRONTIER</div><div style={{fontSize:small?46:82,fontWeight:900,letterSpacing:small?3:5,color:brand.text,lineHeight:1.05}}>霓虹防线 · 飞机大战</div></div></div>};
const Label:React.FC<{text:string;accent?:string;delay:number}>=({text,accent=brand.cyan,delay})=>{const frame=useCurrentFrame(),progress=ease(frame,delay,15);return <div style={{opacity:progress,transform:`translateX(${interpolate(progress,[0,1],[-36,0])}px)`,borderLeft:`4px solid ${accent}`,paddingLeft:16,fontSize:31,color:brand.text,fontWeight:800,letterSpacing:2,textShadow:`0 0 16px ${accent}`}}>{text}</div>};

const Open:React.FC=()=>{const frame=useCurrentFrame(),scan=interpolate(frame,[0,72],[-10,110]);return <AbsoluteFill style={{background:`radial-gradient(circle at 18% 20%,#292568 0%,${brand.ink} 48%)`,overflow:'hidden',padding:'140px 150px'}}><div style={{position:'absolute',top:`${scan}%`,left:0,right:0,height:2,background:brand.cyan,boxShadow:`0 0 32px 8px ${brand.cyan}`,opacity:.65}}/><div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(#58e7ff0d 1px,transparent 1px),linear-gradient(90deg,#58e7ff0d 1px,transparent 1px)',backgroundSize:'54px 54px'}}/><Wordmark/><div style={{position:'absolute',left:154,bottom:160,display:'flex',gap:22,color:'#aeb9ff',fontSize:28,letterSpacing:4,fontWeight:700}}><span style={{color:brand.cyan}}>无尽火力</span><span>·</span><span style={{color:brand.pink}}>Boss 弹幕</span><span>·</span><span style={{color:brand.gold}}>本地排行榜</span></div></AbsoluteFill>};

const Battlefield:React.FC=()=>{const frame=useCurrentFrame(),zoom=interpolate(frame,[0,70],[.88,1.05]),x=interpolate(frame,[0,70],[90,-44]),fade=interpolate(frame,[0,9,62,70],[0,1,1,0]);return <AbsoluteFill style={{background:brand.ink,opacity:fade,overflow:'hidden'}}><Img src={staticFile('game-running.png')} style={{position:'absolute',width:'100%',height:'100%',objectFit:'cover',transform:`scale(${zoom}) translateX(${x}px)`,filter:'saturate(1.12) contrast(1.05)'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(90deg,#05061ae6 0%,#05061a55 52%,transparent 100%)'}}/><div style={{position:'absolute',left:120,top:160,display:'grid',gap:28}}><div style={{color:'#aeb9ff',fontSize:23,fontWeight:800,letterSpacing:7}}>NEON COMBAT SYSTEM</div><Label delay={8} text="自动射击 · 四向闪避"/><Label delay={23} text="强化拾取 · 技能充能" accent={brand.pink}/><Label delay={38} text="突破四道 Boss 防线" accent={brand.gold}/></div></AbsoluteFill>};

const Fighters:React.FC=()=>{const frame=useCurrentFrame(),cards=[{file:'player-ship.png',name:'蔚蓝风暴',skill:'冲击波 · 范围清场',color:brand.cyan},{file:'player-silver-stealth.png',name:'银翼杀手',skill:'隐匿 · 短暂无敌',color:'#dcecff'},{file:'player-green-ninja.png',name:'青岚影忍',skill:'援护 · 双僚机支援',color:'#65ff9a'}];return <AbsoluteFill style={{background:`radial-gradient(circle at 50% 120%,#172b66,${brand.ink} 62%)`,padding:'112px 120px'}}><div style={{fontSize:25,color:'#aeb9ff',letterSpacing:7,fontWeight:800}}>CHOOSE YOUR FIGHTER</div><div style={{fontSize:67,color:brand.text,fontWeight:900,marginTop:15}}>三架战机，三种战术</div><div style={{display:'flex',gap:28,marginTop:64}}>{cards.map((card,index)=>{const progress=ease(frame,2+index*6,18);return <div key={card.name} style={{flex:1,minHeight:306,border:`2px solid ${card.color}`,borderRadius:24,background:'#10133de8',padding:30,opacity:progress,transform:`translateY(${interpolate(progress,[0,1],[80,0])}px)`,boxShadow:`0 0 28px ${card.color}33`}}><Img src={staticFile(card.file)} style={{height:120,width:150,objectFit:'contain',display:'block',margin:'0 auto 20px'}}/><div style={{fontSize:34,color:card.color,fontWeight:900,textAlign:'center'}}>{card.name}</div><div style={{fontSize:20,color:'#c6d1ff',textAlign:'center',marginTop:11}}>{card.skill}</div></div>})}</div></AbsoluteFill>};

const Outro:React.FC=()=>{const frame=useCurrentFrame(),main=ease(frame,0,18);return <AbsoluteFill style={{background:`radial-gradient(circle at 50% 56%,#202367 0%,${brand.ink} 62%)`,overflow:'hidden',display:'grid',placeItems:'center'}}><div style={{position:'absolute',width:900,height:900,border:`2px solid ${brand.cyan}`,borderRadius:'50%',opacity:.14+main*.2,transform:`scale(${.75+main*.35})`,boxShadow:`0 0 80px ${brand.cyan}`}}/><Img src={staticFile('boss-ship.png')} style={{position:'absolute',width:240,right:175,top:112,opacity:.78,filter:'drop-shadow(0 0 22px #ff4fcd)'}}/><div style={{transform:`scale(${.8+main*.2})`,textAlign:'center'}}><Wordmark small/><div style={{marginTop:32,color:brand.cyan,fontSize:32,letterSpacing:7,fontWeight:800,textShadow:`0 0 18px ${brand.cyan}`}}>现在起飞 · 冲破防线</div></div></AbsoluteFill>};
const Sfx:React.FC=()=> <><Sequence from={9} durationInFrames={75}><Audio src={staticFile('audio/transition-soft.mp3')} volume={.34}/></Sequence><Sequence from={64} durationInFrames={80}><Audio src={staticFile('audio/whoosh-big.mp3')} volume={.42}/></Sequence><Sequence from={132} durationInFrames={45}><Audio src={staticFile('audio/swoosh-quick.mp3')} volume={.38}/></Sequence><Sequence from={186} durationInFrames={90}><Audio src={staticFile('audio/riser-cine.mp3')} volume={.42}/></Sequence><Sequence from={201} durationInFrames={90}><Audio src={staticFile('audio/impact-cine.mp3')} volume={.52}/></Sequence><Sequence from={218} durationInFrames={90}><Audio src={staticFile('audio/sparkle.mp3')} volume={.28}/></Sequence></>;
export const AiflMain:React.FC=()=> <AbsoluteFill style={{background:brand.ink}}><Sfx/><Sequence from={NEON_SHOTS.open.from} durationInFrames={NEON_SHOTS.open.duration}><Open/></Sequence><Sequence from={NEON_SHOTS.battlefield.from} durationInFrames={NEON_SHOTS.battlefield.duration}><Battlefield/></Sequence><Sequence from={NEON_SHOTS.fighters.from} durationInFrames={NEON_SHOTS.fighters.duration}><Fighters/></Sequence><Sequence from={NEON_SHOTS.outro.from} durationInFrames={NEON_SHOTS.outro.duration}><Outro/></Sequence></AbsoluteFill>;
